name: 🐛 Bug Report
description: Report a bug or issue with Parserator
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: input
    id: version
    attributes:
      label: Parserator Version
      description: Which version of Parserator are you using?
      placeholder: "e.g., 1.0.0, latest, beta"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core API
        - Chrome Extension
        - VS Code Extension
        - Python SDK
        - Node.js SDK
        - MCP Server
        - Documentation
        - Website
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Parse this data: '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: sample-data
    attributes:
      label: Sample Data
      description: If applicable, provide the input data that caused the issue
      placeholder: Paste the input text or data that caused the problem
      render: text

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: Describe the expected outcome

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your operating system, browser, or development environment
      placeholder: "e.g., Windows 11, Chrome 120, VS Code 1.85, Python 3.11"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or logs about the problem
      placeholder: Any additional information that might help us debug this issue

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true