name: 🔌 Integration Request
description: Request support for a new framework, tool, or platform
title: "[Integration]: "
labels: ["integration", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Request integration with a new framework, tool, or platform. Help us prioritize by providing details about your use case.

  - type: input
    id: framework
    attributes:
      label: Framework/Tool Name
      description: What framework, library, or tool should we integrate with?
      placeholder: "e.g., Zapier, Hugging Face, Apache Airflow, etc."
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Framework Website/Documentation
      description: Link to the official website or documentation
      placeholder: "https://..."

  - type: dropdown
    id: category
    attributes:
      label: Integration Category
      options:
        - AI/ML Framework (LangChain, LlamaIndex, etc.)
        - Agent Platform (AutoGPT, CrewAI, etc.)
        - Data Platform (Databricks, Snowflake, etc.)
        - Automation Tool (Zapier, Make.com, etc.)
        - Development Tool (IDE, CLI, etc.)
        - Business Platform (Salesforce, HubSpot, etc.)
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use Parserator with this tool? What workflow would this enable?
      placeholder: "I want to use Parserator with [framework] to..."
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: Current Workaround
      description: How are you currently solving this problem, if at all?
      placeholder: "Currently I have to..."

  - type: dropdown
    id: users
    attributes:
      label: Potential User Base
      description: How many people do you think would benefit from this integration?
      options:
        - Small (1-10 users)
        - Medium (10-100 users)
        - Large (100-1000 users)
        - Very Large (1000+ users)
        - Unsure

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical details about how this integration should work
      placeholder: "The integration should support..."

  - type: textarea
    id: example
    attributes:
      label: Example Code/Usage
      description: If you have ideas about the API or usage, share them here
      placeholder: |
        ```python
        # Example of how the integration might work
        ```
      render: markdown

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help with this integration?
      options:
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can help with code (if guided)
        - label: I can provide feedback during development

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true